language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MemoizationPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.2
  core_threshold: 0.2
  fallback_action_name: action_default_fallback
